#!/usr/bin/env bash

# Define the key file name and passphrase
KEY_FILE="$HOME/.ssh/school"
PASSPHRASE="betty"

# Create the .ssh directory if it doesn't exist
mkdir -p "$HOME/.ssh"

# Set correct permissions for the .ssh directory
chmod 700 "$HOME/.ssh"

# Generate the RSA key pair
ssh-keygen -t rsa -b 4096 -f "$KEY_FILE" -N "$PASSPHRASE"

echo "SSH key pair generated at $KEY_FILE"