#!/usr/bin/env bash
# script for running command whoami using by changing user/ alternating user / under different users
if [ "$#" -ne 1 ]; then
	echo "Invalid usage"
	exit 1
fi

# run whoami as a specified user
sudo -u "$1" whoami 
