#!/usr/bin/env bash
# setting a different user to run web server nginx

sudo useradd -r nginx
sudo sed -i 's/^user.*/user nginx/' /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /var/www/html
sudo chown -R nginx:nginx /var/log/nginx
sudo service nginx restart
