#!/usr/bin/env bash
# this script automates an establishment of a load balancer using roundrobin alg

sudo apt update -y
sudo apt install haproxy
sudo sed -i '$a\frontend front-web\n\tbind *:80\n\tdefault_backend backend-server\nbackend backend-server\n\tbalance roundrobin\n\tserver web-01 44.222.227.193:80 check\n\tserver web-02 34.228.16.92:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
