#!/usr/bin/env bash
# The script below adds a listen directive that makes it possible to listen to port 80
service nginx start
sed -i '/^\tlisten/a \\tlisten 80;' /etc/nginx/sites-available/default
service nginx reload
