#!/usr/bin/env bash
# This script taked params from commandline and use them to copy file to remote server
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4
if [[ $1 && $2 && $3 && $4 ]]; then
    scp -i PATH_TO_SSH_KEY PATH_TO_FILE USERNAME@IP 
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
