#!/usr/bin/env bash
#This script can automat an installation of nginx on a web server

sudo apt install nginx -y
sudo echo "<h1>Holberton School</h1>" > /var/www/html/index.html
sudo service nginx start
